FROM ubuntu:18.04

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends wget build-essential jq tree git ca-certificates curl \
    libgl-dev libosmesa6-dev libglu1-mesa-dev  && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    apt-get remove --purge -y && \
    mkdir /arctern-docs && \
    rm -rf /var/lib/apt/lists/*  && \
    wget https://mirror.bit.edu.cn/apache/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz && \
    tar -zxvf spark-3.0.0-bin-hadoop2.7.tgz -C /opt/ && \
    cd /opt/ &&  wget https://piccolo.link/sbt-1.3.13.tgz && \
    tar -zxvf sbt-1.3.13.tgz && \
    apt-get update && \
    apt-get install openjdk-8-jdk -y

COPY docker/docker-entrypoint.sh /opt/docker-entrypoint.sh

ENTRYPOINT [ "/opt/docker-entrypoint.sh" ]
